=== FreddyMSchubert/MMUCraft/minecraft/main/data/validation/schemas/item/item.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "item.schema.json",
	"title": "Composable fake item",
	"$defs": {
		"resourceIdentifier": {
			"type": "string",
			"pattern": "^[a-z0-9._-]+(?:/[a-z0-9._-]+)*$"
		},
		"namespacedResourceIdentifier": {
			"type": "string",
			"pattern": "^[a-z0-9._-]+:[a-z0-9._-]+(?:/[a-z0-9._-]+)*$"
		}
	},
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"title": {
			"type": "string",
			"minLength": 1
		},
		"id": {
			"$ref": "#/$defs/resourceIdentifier"
		},
		"craftable": {
			"$ref": "./components/craftable.schema.json"
		},
		"baseItemOverride": {
			"$ref": "#/$defs/namespacedResourceIdentifier"
		},
		"modelType": {
			"type": "string",
			"enum": ["basic", "basic-3d", "charm", "cosmetic"]
		},
		"rarity": {
			"type": "string",
			"enum": ["common", "uncommon", "rare", "epic", "legendary", "mythical"]
		},
		"maxStackSize": {
			"oneOf": [
				{
					"type": "integer",
					"minimum": 1,
					"maximum": 99
				}
			]
		},
		"fireproof": {
			"type": "boolean"
		},
		"tooltips": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"shopPurchasable": {
			"$ref": "./components/shop-purchasable.schema.json"
		},
		"particleEmission": {
			"$ref": "./components/particle-emission.schema.json"
		},
		"charm": {
			"$ref": "./components/charm.schema.json"
		},
		"consumable": {
			"$ref": "./components/consumable.schema.json"
		},
		"dyeable": {
			"$ref": "./components/dyeable.schema.json"
		},
		"decoBlock": {
			"$ref": "./components/deco-block.schema.json"
		},
		"equippableCharm": {
			"$ref": "./components/equippable-charm.schema.json"
		},
		"equippableCosmetic": {
			"$ref": "./components/equippable-cosmetic.schema.json"
		},
		"disc": {
			"$ref": "./components/disc.schema.json"
		},
		"fish": {
			"$ref": "./components/fish.schema.json"
		}
	},
	"required": ["title", "id", "modelType", "rarity", "maxStackSize", "tooltips"],
	"allOf": [
		{
			"if": { "required": ["particleEmission"] },
			"then": {
				"anyOf": [{ "required": ["decoBlock"] }, { "required": ["equippableCosmetic"] }]
			}
		},
		{
			"if": {
				"required": ["equippableCosmetic"]
			},
			"then": {
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^cosmetic-"
					}
				}
			}
		},
		{
			"if": {
				"required": ["fish"]
			},
			"then": {
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^fish-"
					}
				}
			}
		},
		{
			"if": {
				"required": ["charm"]
			},
			"then": {
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^(?:charm|cosmetic)-"
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"modelType": {
						"const": "charm"
					}
				},
				"required": ["modelType"]
			},
			"then": {
				"required": ["equippableCharm"]
			}
		},
		{
			"if": {
				"properties": {
					"modelType": {
						"const": "cosmetic"
					}
				},
				"required": ["modelType"]
			},
			"then": {
				"required": ["equippableCosmetic"]
			}
		},
		{
			"not": {
				"required": ["equippableCharm", "equippableCosmetic"]
			}
		}
	]
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/amogus/item.json
{
	"title": "Amogus Hat",
	"id": "cosmetic-amogus",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [
		"When the impostor is sus"
	],
	"shopPurchasable": {
		"priceDabloons": 35,
		"description": "",
		"unlockWeight": 100,
		"unlockMessage": "Unlocked cosmetic: Amogus Hat."
	},
	"equippableCosmetic": {},
	"dyeable": {
		"tintColor": "#FF0000"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/_true-hats/sun-hat/item.json
{
	"title": "Sun Hat",
	"id": "cosmetic-sun-hat",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": ["Perfect for vampires"],
	"shopPurchasable": {
		"membersOnly": false,
		"priceDabloons": 42,
		"description": "",
		"unlockWeight": 10000,
		"unlockMessage": "Unlocked cosmetic: Sun Hat.",
		"tags": ["beach", "straw hat"]
	},
	"equippableCosmetic": {},
	"dyeable": {
		"tintColor": "#f1337f"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/fish/uncommon/jellyfish/item.json
{
	"title": "Jellyfish",
	"id": "fish-jellyfish",
	"modelType": "basic",
	"rarity": "uncommon",
	"maxStackSize": 64,
	"tooltips": [
		"Jellyfish have no brain, heart, or bones, relying on a simple nerve net."
	],
	"fish": {
		"angle": "BL",
		"tags": [
			"ocean"
		],
		"size": {
			"averageLengthCm": 25,
			"textureLengthPixels": 17.67767
		},
		"furnaceResult": "tentacle"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/charm/held/backpacks/magic/item.json
{
	"title": "Magic Backpack",
	"id": "charm-magic-backpack",
	"modelType": "basic",
	"rarity": "rare",
	"maxStackSize": 1,
	"tooltips": [
		"Right click to open.",
		"Holds 27 slots."
	],
	"charm": {
		"charmId": 46,
		"minLevel": 1,
		"maxLevel": 1,
		"levels": [
			{
				"level": 1,
				"abilityStatusCurrent": "Opens a 27-slot backpack when used.",
				"abilityStatusRelative": "",
				"upgradeIngredients": []
			}
		]
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/charm/equipped/heart-diamond/item.json
{
	"title": "Heart of Diamond Charm",
	"id": "charm-heart-diamond",
	"modelType": "basic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [
		"Slightly wet and pulsing.",
		"(6 extra hearts)"
	],
	"charm": {
		"charmId": 5
	},
	"equippableCharm": {
		"equipmentSlot": "chest",
		"equippableAssetId": "heart_diamond__charm"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/_glasses/popout_eyes/item.json
{
	"title": "Popout Eyes",
	"id": "cosmetic-popout-eyes",
	"modelType": "cosmetic",
	"rarity": "uncommon",
	"maxStackSize": 1,
	"tooltips": ["They look eye-palling."],
	"shopPurchasable": {
		"gameplayToggle": "circus",
		"membersOnly": false,
		"priceDabloons": 42,
		"description": "",
		"unlockWeight": 100,
		"unlockMessage": "Unlocked cosmetic: Popout Eyes (very freaky).",
		"tags": ["bulging eyes"]
	},
	"equippableCosmetic": {}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/fish/common/anchovy/item.json
{
	"title": "Anchovy",
	"id": "fish-anchovy",
	"modelType": "basic",
	"rarity": "common",
	"maxStackSize": 64,
	"tooltips": [
		"Anchovies form immense schools whose synchronized turns confuse predators."
	],
	"fish": {
		"angle": "L",
		"tags": [
			"ocean"
		],
		"size": {
			"averageLengthCm": 15,
			"textureLengthPixels": 12
		},
		"furnaceResult": "red_meat"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/candle/item.json
{
	"title": "Candle",
	"id": "cosmetic-candle",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [],
	"shopPurchasable": {
		"priceDabloons": 35,
		"description": "A wardrobe cosmetic unlock for Candle.",
		"unlockPriority": 0
	},
	"equippableCosmetic": {},
	"dyeable": {
		"tintColor": "#d8d29d"
	}
}
