=== FreddyMSchubert/MMUCraft/minecraft/main/data/validation/schemas/item/item.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "item.schema.json",
	"title": "Composable fake item",
	"$defs": {
		"resourceIdentifier": {
			"type": "string",
			"pattern": "^[a-z0-9._-]+(?:/[a-z0-9._-]+)*$"
		},
		"namespacedResourceIdentifier": {
			"type": "string",
			"pattern": "^[a-z0-9._-]+:[a-z0-9._-]+(?:/[a-z0-9._-]+)*$"
		}
	},
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"title": {
			"type": "string",
			"minLength": 1
		},
		"id": {
			"$ref": "#/$defs/resourceIdentifier"
		},
		"craftable": {
			"$ref": "./components/craftable.schema.json"
		},
		"baseItemOverride": {
			"$ref": "#/$defs/namespacedResourceIdentifier"
		},
		"modelType": {
			"type": "string",
			"enum": ["basic", "basic-3d", "charm", "cosmetic"]
		},
		"rarity": {
			"type": "string",
			"enum": ["common", "uncommon", "rare", "epic", "legendary", "mythical"]
		},
		"maxStackSize": {
			"oneOf": [
				{
					"type": "integer",
					"minimum": 1,
					"maximum": 99
				}
			]
		},
		"fireproof": {
			"type": "boolean"
		},
		"tooltips": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"shopPurchasable": {
			"$ref": "./components/shop-purchasable.schema.json"
		},
		"particleEmission": {
			"$ref": "./components/particle-emission.schema.json"
		},
		"charm": {
			"$ref": "./components/charm.schema.json"
		},
		"consumable": {
			"$ref": "./components/consumable.schema.json"
		},
		"dyeable": {
			"$ref": "./components/dyeable.schema.json"
		},
		"decoBlock": {
			"$ref": "./components/deco-block.schema.json"
		},
		"equippableCharm": {
			"$ref": "./components/equippable-charm.schema.json"
		},
		"equippableCosmetic": {
			"$ref": "./components/equippable-cosmetic.schema.json"
		},
		"disc": {
			"$ref": "./components/disc.schema.json"
		},
		"fish": {
			"$ref": "./components/fish.schema.json"
		}
	},
	"required": ["title", "id", "modelType", "rarity", "maxStackSize", "tooltips"],
	"allOf": [
		{
			"if": { "required": ["particleEmission"] },
			"then": {
				"anyOf": [{ "required": ["decoBlock"] }, { "required": ["equippableCosmetic"] }]
			}
		},
		{
			"if": {
				"required": ["equippableCosmetic"]
			},
			"then": {
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^cosmetic-"
					}
				}
			}
		},
		{
			"if": {
				"required": ["fish"]
			},
			"then": {
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^fish-"
					}
				}
			}
		},
		{
			"if": {
				"required": ["charm"]
			},
			"then": {
				"properties": {
					"id": {
						"type": "string",
						"pattern": "^(?:charm|cosmetic)-"
					}
				}
			}
		},
		{
			"if": {
				"properties": {
					"modelType": {
						"const": "charm"
					}
				},
				"required": ["modelType"]
			},
			"then": {
				"required": ["equippableCharm"]
			}
		},
		{
			"if": {
				"properties": {
					"modelType": {
						"const": "cosmetic"
					}
				},
				"required": ["modelType"]
			},
			"then": {
				"required": ["equippableCosmetic"]
			}
		},
		{
			"not": {
				"required": ["equippableCharm", "equippableCosmetic"]
			}
		}
	]
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/pirate-hat/item.json
{
	"title": "Pirate Hat",
	"id": "cosmetic-pirate",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [],
	"shopPurchasable": {
	"priceDabloons": 50,
		"description": "Unlock the Pirate Hat cosmetic.",
		"unlockWeight": 100,
		"unlockMessage": "Unlocked cosmetic: Pirate Hat."
	},
	"equippableCosmetic": {}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/fish/blobfish/item.json
{
	"title": "Blobfish",
	"id": "fish-blobfish",
	"modelType": "basic",
	"rarity": "uncommon",
	"maxStackSize": 1,
	"tooltips": [],
	"fish": {
		"shape": "fish_shadow_weird",
		"size": 0.5,
		"secondsAwayFromBobber": 2,
		"approachSeconds": 0.5,
		"retreatSeconds": 2,
		"retreatDistance": 1,
		"averageCatchSeconds": 30,
		"struggleSeconds": 5
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/book_stack/item.json
{
	"title": "Book Stack",
	"id": "cosmetic-book-stack",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [
		"A stack of some nostalgic, iconic books."
	],
	"shopPurchasable": {
		"priceDabloons": 35,
		"description": "A stack of some nostalgic, iconic books.",
		"unlockWeight": 50,
		"unlockMessage": "Unlocked cosmetic: Book Stack."
	},
	"equippableCosmetic": {}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/ice-cream/item.json
{
	"title": "Ice Cream Hat",
	"id": "cosmetic-ice-cream",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [],
	"shopPurchasable": {
		"priceDabloons": 35,
		"description": "",
		"unlockWeight": 50,
		"unlockMessage": "Unlocked cosmetic: Ice Cream Hat."
	},
	"equippableCosmetic": {},
	"dyeable": {
		"tintColor": "#835432"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/propeller-hat/item.json
{
	"title": "Propeller Hat",
	"id": "cosmetic-propeller",
	"modelType": "cosmetic",
	"rarity": "common",
	"maxStackSize": 1,
	"tooltips": [],
	"shopPurchasable": {
		"priceDabloons": 35,
		"description": "A wardrobe cosmetic unlock for Propeller Hat.",
		"unlockWeight": 25,
		"unlockMessage": "Unlocked cosmetic: Propeller Hat."
	},
	"equippableCosmetic": {}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/fish/common/barbel_steed/item.json
{
	"title": "Barbel Steed",
	"id": "fish-barbel_steed",
	"modelType": "basic",
	"rarity": "common",
	"maxStackSize": 64,
	"tooltips": [
		"Its whiskers read river currents while its powerful tail holds steady in rapids."
	],
	"fish": {
		"angle": "L",
		"tags": [
			"river"
		],
		"size": {
			"averageLengthCm": 60,
			"textureLengthPixels": 15
		},
		"furnaceResult": "white_meat"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/fish/rare/mooneel/item.json
{
	"title": "Mooneel",
	"id": "fish-mooneel",
	"modelType": "basic",
	"rarity": "rare",
	"maxStackSize": 64,
	"tooltips": [
		"It rises from deep crevices only when moonlight reaches the water."
	],
	"fish": {
		"angle": "BL",
		"tags": [
			"waning"
		],
		"size": {
			"averageLengthCm": 120,
			"textureLengthPixels": 18.384776
		},
		"furnaceResult": "white_meat"
	}
}

=== FreddyMSchubert/MMUCraft/minecraft/main/data/data/items/cosmetics/_true-hats/sombreronn/item.json
{
	"title": "Sombreronn",
	"id": "cosmetic-sombreronn",
	"modelType": "cosmetic",
	"rarity": "legendary",
	"maxStackSize": 1,
	"tooltips": ["Nevermind, this may be too big O.o"],
	"shopPurchasable": {
		"gameplayToggle": "inventors",
		"membersOnly": false,
		"priceDabloons": 300,
		"description": "",
		"unlockWeight": 10,
		"unlockMessage": "Unlocked cosmetic: Sombreronn.",
		"tags": ["mexican", "mexico", "sun hat", "large", "big", "huge", "giant"]
	},
	"equippableCosmetic": {}
}
